// send an email to recipient with subject and body
function sendEmail(recipient, subject, body) {
  Email.send({
      SecureToken: "f1335f10-633a-47ab-9976-808dbc7e3813",
      To : recipient,
      From : "remindappnotifications@gmail.com",
      Subject : subject,
      Body : body
  }).then(
    message => {
      console.log(message);
      
      if(message != "OK") {
        alert("Error: could not send email. Please check that you entered a valid email adress.");
      }
    }
  );
}

// example
// sendEmail("dykstrlu@mail.gvsu.edu", "test", "this is the body");

// send notification
function notify(message) {
  if(Notification.permission !== "granted") {
    Notification.requestPermission().then(message => {
      new Notification(message);
    });
  } else {
    new Notification(message);
  }
}

// email reminder given its index in list
function emailReminder(index) {
  var remind = reminders[index];
  var body = remind.body == ""? remind.header : remind.body;
  
  sendEmail(settings.email, remind.header, 
            "Reminder at " + remind.time + ":<br>" + body
           + "<br><br><i>- Generated by <a href=\"https://termprojectremindapp.shanebailey5.repl.co/\">RemindApp</a></i>");
}

// check for notifications | not working
function checkNotifications() {
  var date = new Date();
  var time = convertTime(date.getHours() + ":" + date.getMinutes());
  var today = dateString(new Date());

  console.log(today);
  console.log(time);
  
  for(var i=0;i<reminders.length;i++) {
    if(reminders[i].date === today && reminders[i].time === time && !reminders[i].notified) {
      notify(reminders[i].header);
      emailReminder(i);
      reminders[i].notified = true;
      save();
      console.log("sent: " + reminders[i].header);
    }
  }
}

if(Notification.permission !== "granted") {
  Notification.requestPermission();
}

setInterval(checkNotifications, 5000);